navbar_name:
  default: "Home|New Topics|Search|Users"
  type: list
  description: name (or image) for navigation bar

navbar_location:
  default: "/categories|/latest|/search|/u"
  type: list
  description: URLs for navigation bar 
