navbar_name:
  default: "Home|New Topics|Search|Users"
  type: list
  description: name (or image) for navigation bar

navbar_location:
  default: "/categories|/latest|/search|/u"
  type: list
  description: URLs for navigation bar 

show_when_anon:
  default: true
  type: bool
  description: whether to show the navbar when the user is not logged in